from fastapi import APIRouter

from app.api.v1 import (
    accounting,
    approvals,
    attendance,
    audit,
    auth,
    backup,
    billing,
    branches,
    catalog,
    collections,
    command_center,
    companies,
    compliance,
    customers,
    dashboard,
    dispatch,
    field_sales,
    fleet,
    gst,
    health,
    hr,
    imports,
    industry,
    leave,
    notifications,
    payroll,
    portal,
    pos,
    pricing,
    printing,
    procurement,
    projects,
    receipts,
    sales,
    search,
    subscription,
    suppliers,
    system_health,
    tally_export,
    tenants,
    users,
    warehouse_ops,
    warehouses,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(tenants.router)
api_router.include_router(industry.router)
api_router.include_router(companies.router)
api_router.include_router(branches.router)
api_router.include_router(warehouses.router)
api_router.include_router(users.router)
api_router.include_router(imports.router)
api_router.include_router(catalog.router)
api_router.include_router(customers.router)
api_router.include_router(projects.router)
api_router.include_router(sales.router)
api_router.include_router(pos.router)
api_router.include_router(printing.router)
api_router.include_router(dashboard.router)
api_router.include_router(fleet.router)
api_router.include_router(dispatch.router)
api_router.include_router(warehouse_ops.router)
api_router.include_router(suppliers.router)
api_router.include_router(procurement.router)
api_router.include_router(collections.router)
api_router.include_router(field_sales.router)
api_router.include_router(accounting.router)
api_router.include_router(gst.router)
api_router.include_router(compliance.router)
api_router.include_router(tally_export.router)
api_router.include_router(portal.router)
api_router.include_router(notifications.router)
api_router.include_router(approvals.router)
api_router.include_router(audit.router)
api_router.include_router(system_health.router)
api_router.include_router(backup.router)
api_router.include_router(command_center.router)
api_router.include_router(pricing.router)
api_router.include_router(subscription.router)
api_router.include_router(billing.router)
api_router.include_router(hr.router)
api_router.include_router(attendance.router)
api_router.include_router(leave.router)
api_router.include_router(payroll.router)
api_router.include_router(receipts.router)
api_router.include_router(search.router)
