from fastapi import APIRouter

from app.api.v1 import (
    accounting,
    admissions,
    analytics,
    announcements,
    approvals,
    attendance,
    audit,
    auth,
    backup,
    billing,
    branches,
    catalog,
    collections,
    command_center,
    companies,
    compliance,
    crm,
    customers,
    dashboard,
    dispatch,
    education,
    examinations,
    fee_payment,
    fees,
    field_sales,
    fleet,
    gst,
    guardian_portal,
    health,
    homework,
    hostel,
    hr,
    imports,
    industry,
    jewellery,
    laboratory,
    leave,
    library,
    notifications,
    payroll,
    platform_admin,
    portal,
    pos,
    pricing,
    public,
    printing,
    procurement,
    projects,
    receipts,
    reports,
    sales,
    school_dashboard,
    search,
    serial,
    student_attendance,
    subscription,
    webhooks,
    suppliers,
    support,
    system_health,
    tally_export,
    timetable,
    transport,
    tenant,
    tenants,
    users,
    warehouse_ops,
    warehouses,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(tenants.router)
api_router.include_router(industry.router)
api_router.include_router(laboratory.router)
api_router.include_router(jewellery.router)
api_router.include_router(companies.router)
api_router.include_router(branches.router)
api_router.include_router(warehouses.router)
api_router.include_router(users.router)
api_router.include_router(imports.router)
api_router.include_router(catalog.router)
api_router.include_router(customers.router)
api_router.include_router(crm.router)
api_router.include_router(projects.router)
api_router.include_router(sales.router)
api_router.include_router(pos.router)
api_router.include_router(printing.router)
api_router.include_router(dashboard.router)
api_router.include_router(fleet.router)
api_router.include_router(dispatch.router)
api_router.include_router(warehouse_ops.router)
api_router.include_router(suppliers.router)
api_router.include_router(procurement.router)
api_router.include_router(collections.router)
api_router.include_router(field_sales.router)
api_router.include_router(education.router)
api_router.include_router(admissions.router)
api_router.include_router(announcements.router)
api_router.include_router(analytics.router)
api_router.include_router(school_dashboard.router)
api_router.include_router(student_attendance.router)
api_router.include_router(timetable.router)
api_router.include_router(examinations.router)
api_router.include_router(homework.router)
api_router.include_router(fees.router)
api_router.include_router(fee_payment.router)
api_router.include_router(guardian_portal.router)
api_router.include_router(transport.router)
api_router.include_router(library.router)
api_router.include_router(hostel.router)
api_router.include_router(accounting.router)
api_router.include_router(gst.router)
api_router.include_router(compliance.router)
api_router.include_router(tally_export.router)
api_router.include_router(portal.router)
api_router.include_router(platform_admin.router)
api_router.include_router(notifications.router)
api_router.include_router(approvals.router)
api_router.include_router(audit.router)
api_router.include_router(system_health.router)
api_router.include_router(backup.router)
api_router.include_router(command_center.router)
api_router.include_router(pricing.router)
api_router.include_router(public.router)
api_router.include_router(subscription.router)
api_router.include_router(billing.router)
api_router.include_router(hr.router)
api_router.include_router(attendance.router)
api_router.include_router(leave.router)
api_router.include_router(payroll.router)
api_router.include_router(receipts.router)
api_router.include_router(reports.router)
api_router.include_router(search.router)
api_router.include_router(serial.router)
api_router.include_router(webhooks.router)
api_router.include_router(support.router)
api_router.include_router(tenant.router)
