/** Industry Image Registry for all 25 supported business profiles in MaterialOS.
 * Each image is stored under /photos/industries/<slug>.webp. */
export const INDUSTRY_IMAGES: Record<string, string> = {
  building_materials: "/photos/industries/building_materials.webp",
  retail: "/photos/industries/retail.webp",
  pharmacy: "/photos/industries/pharmacy.webp",
  ecommerce: "/photos/industries/ecommerce.webp",
  fmcg: "/photos/industries/fmcg.webp",
  auto_parts: "/photos/industries/auto_parts.webp",
  food_beverage: "/photos/industries/food_beverage.webp",
  chemical: "/photos/industries/chemical.webp",
  computer_hardware: "/photos/industries/computer_hardware.webp",
  furniture: "/photos/industries/furniture.webp",
  book_publishing: "/photos/industries/book_publishing.webp",
  travel: "/photos/industries/travel.webp",
  electrical: "/photos/industries/electrical.webp",
  paper_mill: "/photos/industries/paper_mill.webp",
  paint: "/photos/industries/paint.webp",
  mobile: "/photos/industries/mobile.webp",
  garments: "/photos/industries/garments.webp",
  jewellery: "/photos/industries/jewellery.webp",
  agriculture: "/photos/industries/agriculture.webp",
  stationery: "/photos/industries/stationery.webp",
  electronics: "/photos/industries/electronics.webp",
  real_estate: "/photos/industries/real_estate.webp",
  grocery: "/photos/industries/grocery.webp",
  printing_press: "/photos/industries/printing_press.webp",
  laboratory: "/photos/industries/laboratory.webp",
};

/** Pre-configured native modules for each industry profile */
export const INDUSTRY_MODULES: Record<string, string[]> = {
  building_materials: ["Dual-UOM (Kg/Bags)", "Contractor Credit", "Dispatch Board", "GST E-Way"],
  retail: ["Barcode POS", "Split Cash/UPI", "MRP Pricing", "Live Stock Ledger"],
  pharmacy: ["Batch & Expiry", "FEFO Auto-Pick", "Near-Expiry Alerts", "Prescription POS"],
  ecommerce: ["Automated Dispatch", "Multi-Warehouse", "Live Cart Sync", "Courier Tracking"],
  fmcg: ["Route Distribution", "Batch Tracking", "Fleet Vans", "Credit Allocations"],
  auto_parts: ["OEM / Part Number", "Compatibility Map", "Core Returns", "Fast Quoting"],
  food_beverage: ["Batch Expiry", "FSSAI Compliance", "Bottling Runs", "Cold-Chain Fleet"],
  chemical: ["Hazardous Batch", "Certificate of Analysis", "Drum Weight", "Statutory Excise"],
  computer_hardware: ["Serial / IMEI", "Warranty Tracking", "RMA Workflow", "Tech Assembly"],
  furniture: ["Dimensional Stock", "Project Invoicing", "Showroom POS", "Custom Job Orders"],
  book_publishing: ["ISBN Tracking", "Royalty Accounting", "Print Production", "Consignment"],
  travel: ["Trip Manifests", "Vehicle Logbook", "Corporate Accounts", "Driver Settlements"],
  electrical: ["Wire Reel Meters", "Project Quotations", "Contractor Ledgers", "Standard Rates"],
  paper_mill: ["Reel GSM & Deckle", "Weight Slitting", "Production Rolls", "Mill Invoicing"],
  paint: ["Tint Formulation", "Base & Stainer", "Batch Matching", "Dealer Discounts"],
  mobile: ["IMEI Tracking", "Brand Warranty", "RMA Repair Board", "Trade-In Values"],
  garments: ["Size / Color Matrix", "Barcode Tagging", "Apparel POS", "Season Markdowns"],
  jewellery: ["Purity & Karat", "Making Charges", "Metal Weight", "Hallmark Records"],
  agriculture: ["Harvest Batches", "Mandis & Lot Pricing", "Moisture & Grade", "Direct Delivery"],
  stationery: ["Volume Wholesale", "Pack Size Conversions", "School Supplies", "Credit Billing"],
  electronics: ["Serial Tracking", "Warranty Claims", "Multi-Branch Stock", "Split Checkout"],
  real_estate: ["Project Milestones", "Escrow Ledgers", "Broker Commissions", "Demand Notes"],
  grocery: ["Barcode Scanning", "Weight Scale POS", "Perishable Batches", "Fast UPI Split"],
  printing_press: ["Live Production Board", "Paper/Ink Stock", "Job Status HUD", "Project Billing"],
  laboratory: ["Sample Barcodes", "Turnaround Timing", "Test Ledgers", "Compliance Reports"],
};
