"""slice 6 customer ecosystem

Revision ID: 06194364b5df
Revises: 2d93f01998b6
Create Date: 2026-09-07 15:54:11.873489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06194364b5df'
down_revision: Union[str, None] = '2d93f01998b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rules',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('required_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_rules_tenant_id'), 'approval_rules', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['approval_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_document_id'), 'approval_requests', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_rule_id'), 'approval_requests', ['rule_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_tenant_id'), 'approval_requests', ['tenant_id'], unique=False)
    op.create_table('portal_documents',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('sales_order_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_documents_customer_id'), 'portal_documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_portal_documents_quotation_id'), 'portal_documents', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_portal_documents_sales_order_id'), 'portal_documents', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_portal_documents_tenant_id'), 'portal_documents', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'users', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_column('users', 'customer_id')
    op.drop_index(op.f('ix_portal_documents_tenant_id'), table_name='portal_documents')
    op.drop_index(op.f('ix_portal_documents_sales_order_id'), table_name='portal_documents')
    op.drop_index(op.f('ix_portal_documents_quotation_id'), table_name='portal_documents')
    op.drop_index(op.f('ix_portal_documents_customer_id'), table_name='portal_documents')
    op.drop_table('portal_documents')
    op.drop_index(op.f('ix_approval_requests_tenant_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_rule_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_document_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_approval_rules_tenant_id'), table_name='approval_rules')
    op.drop_table('approval_rules')
    # ### end Alembic commands ###
