"""supplier billing state and purchase bill tax split

Revision ID: 3a668aa84670
Revises: 06c7abafe072
Create Date: 2026-09-07 11:06:39.586639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a668aa84670'
down_revision: Union[str, None] = '06c7abafe072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_bill_items', sa.Column('cgst_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('purchase_bill_items', sa.Column('sgst_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('purchase_bill_items', sa.Column('igst_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.drop_column('purchase_bill_items', 'tax_amount')
    op.drop_column('purchase_bill_items', 'gst_rate')
    op.add_column('suppliers', sa.Column('billing_state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'billing_state')
    op.add_column('purchase_bill_items', sa.Column('gst_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_bill_items', sa.Column('tax_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.drop_column('purchase_bill_items', 'igst_amount')
    op.drop_column('purchase_bill_items', 'sgst_amount')
    op.drop_column('purchase_bill_items', 'cgst_amount')
    # ### end Alembic commands ###
