"""customer billing state

Revision ID: 5f7354e259bc
Revises: a274ced3ca10
Create Date: 2026-09-07 09:13:03.687007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f7354e259bc'
down_revision: Union[str, None] = 'a274ced3ca10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('billing_state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'billing_state')
    # ### end Alembic commands ###
