"""slice 4 books and compliance

Revision ID: bf485595adef
Revises: 3a668aa84670
Create Date: 2026-09-07 12:15:12.802173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf485595adef'
down_revision: Union[str, None] = '3a668aa84670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_centers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('center_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'center_type', name='uq_cost_centers_name_type')
    )
    op.create_index(op.f('ix_cost_centers_tenant_id'), 'cost_centers', ['tenant_id'], unique=False)
    op.create_table('e_invoices',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('irn', sa.String(length=64), nullable=False),
    sa.Column('ack_number', sa.String(length=30), nullable=False),
    sa.Column('ack_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_qr_code', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', name='uq_einvoice_invoice')
    )
    op.create_index(op.f('ix_e_invoices_invoice_id'), 'e_invoices', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_e_invoices_tenant_id'), 'e_invoices', ['tenant_id'], unique=False)
    op.create_table('e_way_bills',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('ewb_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', name='uq_ewb_invoice')
    )
    op.create_index(op.f('ix_e_way_bills_invoice_id'), 'e_way_bills', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_e_way_bills_tenant_id'), 'e_way_bills', ['tenant_id'], unique=False)
    op.add_column('accounts', sa.Column('parent_account_id', sa.UUID(), nullable=True))
    op.add_column('accounts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f('ix_accounts_parent_account_id'), 'accounts', ['parent_account_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'accounts', ['parent_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('companies', sa.Column('e_invoice_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('companies', sa.Column('e_way_bill_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('journal_lines', sa.Column('cost_center_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_journal_lines_cost_center_id'), 'journal_lines', ['cost_center_id'], unique=False)
    op.create_foreign_key(None, 'journal_lines', 'cost_centers', ['cost_center_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_lines', type_='foreignkey')
    op.drop_index(op.f('ix_journal_lines_cost_center_id'), table_name='journal_lines')
    op.drop_column('journal_lines', 'cost_center_id')
    op.drop_column('companies', 'e_way_bill_enabled')
    op.drop_column('companies', 'e_invoice_enabled')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_parent_account_id'), table_name='accounts')
    op.drop_column('accounts', 'is_active')
    op.drop_column('accounts', 'parent_account_id')
    op.drop_index(op.f('ix_e_way_bills_tenant_id'), table_name='e_way_bills')
    op.drop_index(op.f('ix_e_way_bills_invoice_id'), table_name='e_way_bills')
    op.drop_table('e_way_bills')
    op.drop_index(op.f('ix_e_invoices_tenant_id'), table_name='e_invoices')
    op.drop_index(op.f('ix_e_invoices_invoice_id'), table_name='e_invoices')
    op.drop_table('e_invoices')
    op.drop_index(op.f('ix_cost_centers_tenant_id'), table_name='cost_centers')
    op.drop_table('cost_centers')
    # ### end Alembic commands ###
