"""slice 3 buy and collect

Revision ID: e0d2afad512d
Revises: 3060b4b1c53e
Create Date: 2026-09-07 10:54:33.096313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0d2afad512d'
down_revision: Union[str, None] = '3060b4b1c53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_branch_id'), 'supplier_payments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_company_id'), 'supplier_payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_number'), 'supplier_payments', ['number'], unique=False)
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_tenant_id'), 'supplier_payments', ['tenant_id'], unique=False)
    op.create_table('visits',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('salesperson_user_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_customer_id'), 'visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visits_salesperson_user_id'), 'visits', ['salesperson_user_id'], unique=False)
    op.create_index(op.f('ix_visits_tenant_id'), 'visits', ['tenant_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_branch_id'), 'purchase_orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_company_id'), 'purchase_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_number'), 'purchase_orders', ['number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_warehouse_id'), 'purchase_orders', ['warehouse_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('landed_cost_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_branch_id'), 'goods_receipts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_company_id'), 'goods_receipts', ['company_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_number'), 'goods_receipts', ['number'], unique=False)
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_tenant_id'), 'goods_receipts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_warehouse_id'), 'goods_receipts', ['warehouse_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_item_id'), 'purchase_order_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_tenant_id'), 'purchase_order_items', ['tenant_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_item_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('landed_unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('qc_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_items_goods_receipt_id'), 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_item_id'), 'goods_receipt_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_purchase_order_item_id'), 'goods_receipt_items', ['purchase_order_item_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_tenant_id'), 'goods_receipt_items', ['tenant_id'], unique=False)
    op.create_table('landed_cost_entries',
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocation_method', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landed_cost_entries_goods_receipt_id'), 'landed_cost_entries', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_landed_cost_entries_tenant_id'), 'landed_cost_entries', ['tenant_id'], unique=False)
    op.create_table('purchase_bills',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_bills_branch_id'), 'purchase_bills', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_bills_company_id'), 'purchase_bills', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_bills_goods_receipt_id'), 'purchase_bills', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_purchase_bills_number'), 'purchase_bills', ['number'], unique=False)
    op.create_index(op.f('ix_purchase_bills_supplier_id'), 'purchase_bills', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_bills_tenant_id'), 'purchase_bills', ['tenant_id'], unique=False)
    op.create_table('purchase_bill_items',
    sa.Column('purchase_bill_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_bill_items_item_id'), 'purchase_bill_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_bill_items_purchase_bill_id'), 'purchase_bill_items', ['purchase_bill_id'], unique=False)
    op.create_index(op.f('ix_purchase_bill_items_tenant_id'), 'purchase_bill_items', ['tenant_id'], unique=False)
    op.create_table('supplier_payment_allocations',
    sa.Column('supplier_payment_id', sa.UUID(), nullable=False),
    sa.Column('purchase_bill_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payment_allocations_purchase_bill_id'), 'supplier_payment_allocations', ['purchase_bill_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_supplier_payment_id'), 'supplier_payment_allocations', ['supplier_payment_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_tenant_id'), 'supplier_payment_allocations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_payment_allocations_tenant_id'), table_name='supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payment_allocations_supplier_payment_id'), table_name='supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payment_allocations_purchase_bill_id'), table_name='supplier_payment_allocations')
    op.drop_table('supplier_payment_allocations')
    op.drop_index(op.f('ix_purchase_bill_items_tenant_id'), table_name='purchase_bill_items')
    op.drop_index(op.f('ix_purchase_bill_items_purchase_bill_id'), table_name='purchase_bill_items')
    op.drop_index(op.f('ix_purchase_bill_items_item_id'), table_name='purchase_bill_items')
    op.drop_table('purchase_bill_items')
    op.drop_index(op.f('ix_purchase_bills_tenant_id'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_supplier_id'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_number'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_goods_receipt_id'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_company_id'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_branch_id'), table_name='purchase_bills')
    op.drop_table('purchase_bills')
    op.drop_index(op.f('ix_landed_cost_entries_tenant_id'), table_name='landed_cost_entries')
    op.drop_index(op.f('ix_landed_cost_entries_goods_receipt_id'), table_name='landed_cost_entries')
    op.drop_table('landed_cost_entries')
    op.drop_index(op.f('ix_goods_receipt_items_tenant_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_purchase_order_item_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_item_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_goods_receipt_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_purchase_order_items_tenant_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_item_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_goods_receipts_warehouse_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_tenant_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_company_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_branch_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_purchase_orders_warehouse_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_company_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_branch_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_visits_tenant_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_salesperson_user_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_customer_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_supplier_payments_tenant_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_number'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_company_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_branch_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
