"""slice 2 godown and dispatch

Revision ID: ec190f2c16bd
Revises: 5f7354e259bc
Create Date: 2026-09-07 10:17:55.031299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec190f2c16bd'
down_revision: Union[str, None] = '5f7354e259bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_branch_id'), 'drivers', ['branch_id'], unique=False)
    op.create_index(op.f('ix_drivers_tenant_id'), 'drivers', ['tenant_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ownership', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_branch_id'), 'vehicles', ['branch_id'], unique=False)
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_table('stock_counts',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('counted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_counts_tenant_id'), 'stock_counts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_counts_warehouse_id'), 'stock_counts', ['warehouse_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('to_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_from_warehouse_id'), 'stock_transfers', ['from_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_number'), 'stock_transfers', ['number'], unique=False)
    op.create_index(op.f('ix_stock_transfers_tenant_id'), 'stock_transfers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_warehouse_id'), 'stock_transfers', ['to_warehouse_id'], unique=False)
    op.create_table('trips',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_branch_id'), 'trips', ['branch_id'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_tenant_id'), 'trips', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('stock_count_items',
    sa.Column('stock_count_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('system_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_counts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_count_items_item_id'), 'stock_count_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_count_items_stock_count_id'), 'stock_count_items', ['stock_count_id'], unique=False)
    op.create_index(op.f('ix_stock_count_items_tenant_id'), 'stock_count_items', ['tenant_id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('stock_transfer_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_items_item_id'), 'stock_transfer_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_stock_transfer_id'), 'stock_transfer_items', ['stock_transfer_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_tenant_id'), 'stock_transfer_items', ['tenant_id'], unique=False)
    op.create_table('proof_of_deliveries',
    sa.Column('delivery_challan_id', sa.UUID(), nullable=False),
    sa.Column('receiver_name', sa.String(length=200), nullable=False),
    sa.Column('signature_data_url', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shortage_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_challan_id', name='uq_pod_delivery_challan')
    )
    op.create_index(op.f('ix_proof_of_deliveries_delivery_challan_id'), 'proof_of_deliveries', ['delivery_challan_id'], unique=False)
    op.create_index(op.f('ix_proof_of_deliveries_tenant_id'), 'proof_of_deliveries', ['tenant_id'], unique=False)
    op.create_table('sales_returns',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_returns_invoice_id'), 'sales_returns', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_number'), 'sales_returns', ['number'], unique=False)
    op.create_index(op.f('ix_sales_returns_tenant_id'), 'sales_returns', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sales_returns_warehouse_id'), 'sales_returns', ['warehouse_id'], unique=False)
    op.create_table('sales_return_items',
    sa.Column('sales_return_id', sa.UUID(), nullable=False),
    sa.Column('invoice_item_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_return_items_invoice_item_id'), 'sales_return_items', ['invoice_item_id'], unique=False)
    op.create_index(op.f('ix_sales_return_items_item_id'), 'sales_return_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_sales_return_items_sales_return_id'), 'sales_return_items', ['sales_return_id'], unique=False)
    op.create_index(op.f('ix_sales_return_items_tenant_id'), 'sales_return_items', ['tenant_id'], unique=False)
    op.add_column('delivery_challans', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_delivery_challans_trip_id'), 'delivery_challans', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'delivery_challans', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_challans', type_='foreignkey')
    op.drop_index(op.f('ix_delivery_challans_trip_id'), table_name='delivery_challans')
    op.drop_column('delivery_challans', 'trip_id')
    op.drop_index(op.f('ix_sales_return_items_tenant_id'), table_name='sales_return_items')
    op.drop_index(op.f('ix_sales_return_items_sales_return_id'), table_name='sales_return_items')
    op.drop_index(op.f('ix_sales_return_items_item_id'), table_name='sales_return_items')
    op.drop_index(op.f('ix_sales_return_items_invoice_item_id'), table_name='sales_return_items')
    op.drop_table('sales_return_items')
    op.drop_index(op.f('ix_sales_returns_warehouse_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_tenant_id'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_number'), table_name='sales_returns')
    op.drop_index(op.f('ix_sales_returns_invoice_id'), table_name='sales_returns')
    op.drop_table('sales_returns')
    op.drop_index(op.f('ix_proof_of_deliveries_tenant_id'), table_name='proof_of_deliveries')
    op.drop_index(op.f('ix_proof_of_deliveries_delivery_challan_id'), table_name='proof_of_deliveries')
    op.drop_table('proof_of_deliveries')
    op.drop_index(op.f('ix_stock_transfer_items_tenant_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_stock_transfer_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_item_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_stock_count_items_tenant_id'), table_name='stock_count_items')
    op.drop_index(op.f('ix_stock_count_items_stock_count_id'), table_name='stock_count_items')
    op.drop_index(op.f('ix_stock_count_items_item_id'), table_name='stock_count_items')
    op.drop_table('stock_count_items')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_tenant_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_branch_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_stock_transfers_to_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_tenant_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_number'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_warehouse_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_counts_warehouse_id'), table_name='stock_counts')
    op.drop_index(op.f('ix_stock_counts_tenant_id'), table_name='stock_counts')
    op.drop_table('stock_counts')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_branch_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_tenant_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_branch_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
